server:
    port: 6002

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/workload?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 1809227959

# 配置驼峰
mybatis:
    configuration:
        map-underscore-to-camel-case: true


# 邀请码
invite_code: 6666